FROM nginx:alpine

# Limpa qualquer lixo do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia TUDO da pasta dist (incluindo assets, html, estilos e index)
COPY html/build/dist /usr/share/nginx/html

EXPOSE 80